service: bf-bucket

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws

resources:
  Resources:
    BFBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

package:
  exclude:
    - node_modules/serverless/**
