service: bf-bucket

frameworkVersion: '>=1.2.0 <2.0.0'

provider:
  name: aws

resources:
  Resources:
    BFBucket:
      Type: AWS::S3::Bucket
      Properties:
        # FIXME remove the BucketName line
        BucketName: ${env:BF_BUCKET_NAME}-${opt:stage}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    BFBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: BFBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
              - s3:GetObject
              # FIXME somehow automagically refer to the S3 bucket created earlier
              Resource: arn:aws:s3:::${env:BF_BUCKET_NAME}-${opt:stage}/*

  Outputs:
    BFBucket:
      Value:
        Ref: BFBucket # outputs the bucket name
      Export:
        Name: BFBucket # for use in other stacks

package:
  exclude:
    - node_modules/serverless/**
