service: bf-bucket

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws

resources:
  Resources:
    BFBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

  Outputs:
    BFBucket:
      Value:
        Ref: BFBucket # outputs the S3 ARN for use in other stacks

package:
  exclude:
    - node_modules/serverless/**
